sudo: required

language: cpp

services:
  - docker

before_install:
- docker pull aliced3645/rocksplicator-build

script:
- docker run -v $(pwd):/rocksplicator -v $HOME/docker-root:/root aliced3645/rocksplicator-build /bin/sh -c "cd /rocksplicator; mkdir -p build; cd build; cmake .. ; make -j ; make test"